### ISSUE TITLE
Ignored unknown option { jsdocParser: true }

### ISSUE THREAD

**Issue by charklewis** [hosseinmd/prettier-plugin-jsdoc#10]
I am unable to get prettier to format js docs in my files. I have the following versions and when I run prettier from the CLI I get the below error. 

```
"prettier": "^2.1.2",
"prettier-plugin-jsdoc": "^0.2.4",
```

```
[warn] Ignored unknown option { jsdocParser: true }.
```

My prettier config looks like:

```
{
  "printWidth": 80,
  "tabWidth": 2,
  "useTabs": false,
  "semi": true,
  "singleQuote": false,
  "trailingComma": "es5",
  "bracketSpacing": true,
  "jsxBracketSameLine": false,
  "arrowParens": "avoid",
  "jsdocParser": true
}
```

Prettier respects the other settings in this config but totally ignore the jsDocParser rule. Am I missing any config or is this a bug in the recent release?

**Comment by hosseinmd** [comment]
Your config is right. sometimes you need to close and reopen VSC to stop/start prettier service.

**Comment by charklewis** [comment]
Ah nice, it is now formatting when I save in VSCode. However, it does not format when I run the CLI - I still get that error. Is this expected?

**Comment by hosseinmd** [comment]
> Ah nice, it is now formatting when I save in VSCode. However, it does not format when I run the CLI - I still get that error. Is this expected?

`[warn] Ignored unknown option { jsdocParser: true }.`
This is just a warning, no problem. I could remove jsdocParser from config because that default is true.

**Comment by charklewis** [comment]
Gotcha, does this plugin supposed to run when using the prettier cli? For example `prettier myFile.js --write`. I notice it does not work this way.

**Comment by hosseinmd** [comment]
Yes, it should be work.

**Comment by hosseinmd** [comment]
Please test it with `yarn prettier --write ./src`

**Comment by charklewis** [comment]
Ah yes this works, I must have had my arguments in the wrong order. Thank you for the help!

**Comment by aminya** [comment]
I have the same issue. Running `prettier --write .` doesn't have any effect:
https://github.com/atom-community/prettier-config-atomic/pull/2

```
prettier.config.js 14ms
[warn] Ignored unknown option { jsdocParser: false }.
[warn] Ignored unknown option { tsdoc: true }.
```

**Comment by aminya** [comment]
I fixed this by adding to my `prettier.config.js`. 
```
  plugins: ["prettier-plugin-jsdoc"],
```

**Comment by hosseinmd** [comment]
> I fixed this by adding to my `prettier.config.js`.
> 
> ```
>   plugins: ["prettier-plugin-jsdoc"],
> ```

You should set jsdocParser and tsdoc both true

**Comment by aminya** [comment]
Yeah, that's what I find out. Could you update the docs as this was unclear?

**Comment by hosseinmd** [comment]
I will do it soon.

Thank you
