### ISSUE TITLE
Not formatting function comments

### ISSUE THREAD

**Issue by Remscar** [hosseinmd/prettier-plugin-jsdoc#100]
Hi i've been using this plugin but have found that it won't auto-format function comments for me.

For instance i'll have code like this:

```
  /**
 @notice does a thing
  */
  function doThing
    uint256 number
  ) external;
  ```

But it won't indent the `@notice` to match the indentation with the rest of the comment. Can't figure out what i'm doing wrong, everything else is working properly and I see there is code in the repo for handling comments, but it just doesn't seem to be running.

**Comment by hosseinmd** [comment]
Your function has syntax error

**Comment by Remscar** [comment]
Sorry that my sample code had a syntax error, I have fixed it.
The bug happens whether the function has an error in it or not.
