### ISSUE TITLE
Allow to breaking a line by using '\' or double spaces

### ISSUE THREAD

**Issue by zhangyanwei** [hosseinmd/prettier-plugin-jsdoc#102]
For example, the bellow jsDoc,
```typescript
/**
 * A short description,  
 * A long description.
 */
```
becomes to
```typescript
/**
 * A short description, A long description.
 */
```

Even using '\\', it also will be trimmed.
In my opinion, should keep it if the parser can recognize it.

I think it could be fixed by adding a new branch for the 'break' type at https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/b9d7cc68a6ede9e064df63b1e2612e282f87ee38/src/descriptionFormatter.ts#L220

Or it's better to make each type be configurable rather than write a big function with many branches.

**Comment by hosseinmd** [comment]
You could add dash for your case.
```js
/**
 * - A short description,  
 * - A long description.
 */
```

**Comment by hosseinmd** [comment]
i will support '\' as soon as possible
