### ISSUE TITLE
support jsdoc @ example with <caption>...</caption>

### ISSUE THREAD

**Issue by Aqzhyi** [hosseinmd/prettier-plugin-jsdoc#11]
This is really a wonderful package. But I just ran into an issue about `@example`

## BEFORE

![image](https://user-images.githubusercontent.com/1500206/100479322-d102b300-3128-11eb-9f67-e71415efe46f.png)

## AFTER

![image](https://user-images.githubusercontent.com/1500206/100479336-da8c1b00-3128-11eb-8491-79bc6e906602.png)

## ref

https://jsdoc.app/tags-example.html

**Comment by hosseinmd** [comment]
Hi there, I will check it as soon as possible.

**Comment by hosseinmd** [comment]
There is a temporary solution
Change your code to this
```js
"/**
 * An Example description
 * 
 * @example   <---- add an new line
 *   <caption>message</caption> 
 *
 * export default app
 */
```

**Comment by Aqzhyi** [comment]
It doesn't work.

It is formatting into

```tsx
/**
 * @example
 *   ;<caption>TradingViewChart</caption>
 *   👆
 */
```

And VSCode losing the code highlight.

But even so, it does more convenient for me.

Thank you and your project. 😍

**Comment by hosseinmd** [comment]
Done v0.2.5
