### ISSUE TITLE
Sperate @returns from @param

### ISSUE THREAD

**Issue by RedGuy12** [hosseinmd/prettier-plugin-jsdoc#113]
I would really like it if there was an option to separate the @returns statement from the @param statements for readability.

#### Example
I like this:
![image](https://user-images.githubusercontent.com/61329810/118751595-348fb280-b827-11eb-9bc5-5ab5df9193cb.png)
But with this plugin, Prettier removes the newline and formats it like this:
![image](https://user-images.githubusercontent.com/61329810/118751664-54bf7180-b827-11eb-8326-0e245eb96dcc.png)
I would like an option for Prettier to keep the newline there, and add one if it's not already there.

**Comment by hosseinmd** [comment]
I will add an option for your use case as soon as possible.

**Comment by RedGuy12** [comment]
Yay, TYSM!!
________________________________

**Comment by RedGuy12** [comment]
@hosseinmd Any updates?

**Comment by hosseinmd** [comment]
Fixed in v0.3.23

**Comment by hosseinmd** [comment]
`jsdocSeparateReturnsFromParam` added to options, set it true.
