### ISSUE TITLE
＠type {import(...)} should known the Pascal case

### ISSUE THREAD

**Issue by Aqzhyi** [hosseinmd/prettier-plugin-jsdoc#12]
![Kapture 2020-12-02 at 06 49 57](https://user-images.githubusercontent.com/1500206/100806072-cae33e00-346a-11eb-99c7-e09a88a8cf9f.gif)

BEFORE

```
/** @type{import('@jest/types/build/Config').InitialOptions} */
```

AFTER
> File name '/.../node_modules/@jest/types/build/config.d.ts' differs from already included file name
```
/** @type{import('@jest/types/build/config').initialoptions} */
                                    👆       👆      👆

```

**Comment by hosseinmd** [comment]
Please add a space between tag and type.
/** @type {import('@jest/types/build/Config').InitialOptions} */

**Comment by hosseinmd** [comment]
I think that can be fixed automatically I will work on it as soon as possible.

**Comment by hosseinmd** [comment]
Done https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/42444741bea8c53dd17e5a32629d903d0a503914
