### ISSUE TITLE
tsdoc - Don't replace @defaultValue with @default

### ISSUE THREAD

**Issue by aaronadamsCA** [hosseinmd/prettier-plugin-jsdoc#124]
When I format this TypeScript code:

```ts
interface DialogProps {
  /**
   * Whether the dialog should disable the main content while open
   *
   * @defaultValue true
   */
  modal?: boolean;
}
```

This plugin replaces `@defaultValue` with `@default`. [Per TSDoc docs, the correct tag is `@defaultValue`](https://tsdoc.org/pages/tags/defaultvalue/).

`.prettierrc.cjs`:

```js
module.exports = {
  overrides: [
    {
      files: ["*.ts", "*.tsx"],
      options: {
        tsdoc: true,
      },
    },
  ],
};
```

**Comment by hosseinmd** [comment]
fixed: https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/6eabd150b1ae100b826bd2d4c2cb84f923bb1cc9
release v 0.3.24
