### ISSUE TITLE
Wrapping single-line (`//`) comments

### ISSUE THREAD

**Issue by mbforbes** [hosseinmd/prettier-plugin-jsdoc#126]
Hi there,

First off, thank you so much for making this plugin, it's working fantastic!

I'm hoping to find a solution to also wrap single-line comments (that start with `//`). 

I totally understand if this is out of scope for your plugin—after all, it's explicitly about jsDoc! However, I haven't seen another plugin that does comment wrapping, so I thought it would be worth asking.

Do you think that either,

1. It would make sense to add an option to also wrap `//` comments?

2. If not, I might consider making this modification myself—might you be able to point me roughly towards where I could make these changes? It looks like there are a few places in `parser.ts`, but I don't know my way around the code yet 😅 

Huge thanks!

**Comment by hosseinmd** [comment]
Look good to me

**Comment by hosseinmd** [comment]
You could start from https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/3e53f124c550821c13ea97fb449fe38778cacd7b/src/parser.ts#L54, where we detected comment is block comment
I think for doing this you could just form comments as description with this function https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/3e53f124c550821c13ea97fb449fe38778cacd7b/src/descriptionFormatter.ts#L45

**Comment by mbforbes** [comment]
Awesome, many thanks! I will have a go at this soon™️ 😂

**Comment by hosseinmd** [comment]
We should never do this.
