### ISSUE TITLE
How to use in browser?

### ISSUE THREAD

**Issue by mbforbes** [hosseinmd/prettier-plugin-jsdoc#128]
Apologies for the second question 😅 

I'm hoping to run this plugin in the browser, but I'm not sure how to do that.

Following [Prettier's Browser guide](https://prettier.io/docs/en/browser.html), I'm able to run plugins that prettier has hosted, like the TypeScript one:

```html
<script type="module">
    import prettier from "https://unpkg.com/prettier@2.4.0/esm/standalone.mjs";
    import parserTS from "https://unpkg.com/prettier@2.4.0/esm/parser-typescript.mjs";
    prettier.format("class Foo {}", {
        parser: "typescript",
        plugins: [parserTS],
    });
</script>
```

However, I'm not sure how to run this plugin, which doesn't have an all-in-one file exported. I checked out what was installed in `node_modules/prettier-plugin-jsdoc/` and I see 13 JavaScript files in the `lib/` subfolder. Would they need to be combined in some way?

Again, many thanks for any advice!

**Comment by hosseinmd** [comment]
Hi, I think that could be done with typescript, I will do it as soon as possible

**Comment by mbforbes** [comment]
Ahh, amazing, thank you so much! 🙏

**Comment by hosseinmd** [comment]
V0.3.32 released, check it.

**Comment by mbforbes** [comment]
Oh wow, awesome, I will check it! Thank you!
