### ISSUE TITLE
Add hyphen between symbol and description

### ISSUE THREAD

**Issue by runarberg** [hosseinmd/prettier-plugin-jsdoc#13]
I really prefer to have a hyphen (`-`) separating symbol names (e.g. a param name) and a description. The current behavior is to strip the hyphen, as it is optional in JSDoc, but there are several reasons to prefer it:

* It visually separates the name from the description.
* It is easier to quickly guide my eyes to the name as the thing before the hyphen.
* It prevents the name from becoming a part of the description when it is grammatically logical for it to be the first word in a sentence.

```js
/**
 * @typedef A Description of my type
 * @param {A} a item for the function
 */
```

I purposefully named my symbols `a` as it looks like an indefinite article and is really hard to separate visually from the description. Note how much easier it is to find the name when we put a hyphen between the description and the name:

```js
/**
 * @typedef A - Description of my type
 * @param {A} a - item for the function
 */
```

**Comment by runarberg** [comment]
I don’t use screen readers; but I would like to see an input from such a user, as I can imagine this stylistic choice can make a huge difference in how assistive technology presents this information.

**Comment by runarberg** [comment]
Also note: Some text editors and IDEs might syntax highlight the name making it easier to visually distinguish for those users, but this is by no means universal, as you can see by the vary own syntax highlighter here on GitHub.

**Comment by runarberg** [comment]
Related #9

**Comment by hosseinmd** [comment]
I don't think hyphen be a standard. Vscode highlighting Jsdoc.

**Comment by hosseinmd** [comment]
Do you have a reliable reference for this?

**Comment by runarberg** [comment]
The hyphen is optional in JSDoc, and on the [JSDoc website](https://jsdoc.app/about-block-inline-tags.html) they use a hyphen in their examples.

I’m not a user of VSCode, so I don’t know how it is highlighted, but here on GitHub there is no highlighting the name:

![jsdoc comment on github](https://user-images.githubusercontent.com/3984600/100895161-19e0a180-3472-11eb-8733-467398fdeacb.png)

And here is gitlab without syntax highlighting:

![jsdoc comment on gitlab](https://user-images.githubusercontent.com/3984600/100896942-06363a80-3474-11eb-9951-df13c5680b62.png)

In standard Vim there is no highlighting anywhere in the doc comment:

![jsdoc comment in Vim](https://user-images.githubusercontent.com/3984600/100895563-8fe50880-3472-11eb-8244-e8545cfcb95d.png)

Neither in js-mode with emacs:

![jsdoc comment in emacs](https://user-images.githubusercontent.com/3984600/100896069-17327c00-3473-11eb-84f8-d3fbac22c8aa.png)

js2-mode in emacs shows highlights the name of known tags but not the typescript special `@template`:

![jsdoc comment in emacs using js2-mode](https://user-images.githubusercontent.com/3984600/100896395-6e385100-3473-11eb-99d9-475b08440872.png)

If we put a hyphen before the description we will solve an issue for users of editors and IDEs that don’t highlight the name, while not ruining anything for users of editors that do.

Can we at least make the hyphen optional with a setting?

**Comment by hosseinmd** [comment]
Right, so we should not trim that. so you can add a hyphen at the start of description if you would.

**Comment by runarberg** [comment]
The current behavior is to strip the hyphen:

```
$ diff src/combinators/zip.js <(npx prettier src/combinators/zip.js)
18,19c18,19
<  * @template {unknown[]} A - Tuple type with item type of each input iterator
<  * @param {{ [K in keyof A]: Iterable<A[K]> }} items - The iterators to be zipped
---
>  * @template {unknown[]} A Tuple type with item type of each input iterator
>  * @param {{ [K in keyof A]: Iterable<A[K]> }} items The iterators to be zipped
```

**Comment by hosseinmd** [comment]
Done https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/89704b88e640f00ffec0508a38b012b35b8fc23b v0.2.5
