### ISSUE TITLE
Block quotes are removed

### ISSUE THREAD

**Issue by fb55** [hosseinmd/prettier-plugin-jsdoc#131]
```js
/** > A block quote */
```

turns into

```js
/** A block quote */
```

**Comment by hosseinmd** [comment]
i will do it soon, if you like to do it you could start from this file https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/master/src/descriptionFormatter.ts

**Comment by hosseinmd** [comment]
Fixed
