### ISSUE TITLE
Strips markdown links from start of JSDoc tag descriptions

### ISSUE THREAD

**Issue by jaydenseric** [hosseinmd/prettier-plugin-jsdoc#136]
If you have a tag like this:

```
@param {string} [dir] [Next.js](https://nextjs.org) project directory path.
```

After the first fix, it becomes this:

```
@param {string} [dir] project directory path.
```

Then after a second fix, it becomes this:

```
@param {string} [dir] Project directory path.
```

It is legitimate to start a JSDoc tag description with a markdown link, and there are many examples of this in real world code. This Prettier plugin shouldn't delete them.

**Comment by hosseinmd** [comment]
Fixed in v0.3.26
https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/master/CHANGELOG.md#0326-2021-11-05
