### ISSUE TITLE
Consider using underlines for italics instead of stars to be consistent with prettier's markdown formatting 

### ISSUE THREAD

**Issue by G-Rath** [hosseinmd/prettier-plugin-jsdoc#142]
It didn't really click until today, but currently this plugin converts `_words_` into `*words*` - personally I'm not too fussed by that, except Prettier does the opposite in it's markdown formatter (I think to make it more distinctive vs bold) and I feel like it would be good to be consistent since jsdoc comments are often treated as markdown (at least for formatting).

afaik both `_words_` & `*words*` are allowed in JSDoc for italics, but I also could be wrong.

Happy to implement a PR (both just changing it or adding an option) if you want to see this change :)

**Comment by hosseinmd** [comment]
We just could apply one of that, if you think _words_ is better, Please PR that.
