### ISSUE TITLE
Unspecified or unrecognized code blocks should be left as they are

### ISSUE THREAD

**Issue by beark** [hosseinmd/prettier-plugin-jsdoc#144]
Or there should be some other way of indicating I don't want them formatted. Additionally, I get some _very_ weird results when trying to illustrate a thing with some ASCII-art in aforementioned code block.

Example input:
```ts
/**
 * ```
 * 10
 * |-- 3
 * `-- 4
 * ```
 */
```
Output:
```ts
/**
 * 10
 *
 *     2@^5!~#sdE!_TABLE
 *
 *     `-- 4
 */
```
No idea what that's even _trying_ to do!

**Comment by hosseinmd** [comment]
Plugin thing that is a table but can't format it completely because that wasn't correct table format. This is a bug in recognizing tables.
