### ISSUE TITLE
Feature Request: eslint & eslint-plugin-jsdoc integration

### ISSUE THREAD

**Issue by unicornware** [hosseinmd/prettier-plugin-jsdoc#162]
## Description

I'm attempting to integrate this plugin into my workflow, but it doesn't seem the plugin is integrated with [`eslint-plugin-jsdoc`][1], nor [eslint][2] itself.

Specifically, the lack of support for the [`tagNamePreference`][3] setting in [`eslint-plugin-jsdoc`][1] results in faulty errors regarding tags. 

I'm not entirely sure, but I also suspect that the lack of integration with eslint (or maybe [`prettier-vscode`][4]?) means the following:

- Issues yielded by this plugin are only displayed by directly running `eslint`
  - If I open a file with alleged issues, my editor (VSCode) doesn't show any red squigglies where the plugin identified the issues; I have to run `eslint` to get a full report
- Issues that are auto-fixable are not fixed on save
  - Normally when I save a file that has auto-fixable issues (even if the file doesn't have any changes), those issues are fixed on save. This does not happen with issues yielded by this plugin; I have to run `eslint --fix` instead

## Example

[`tagNamePreference`][3] settings:

```javascript
{
    jsdoc: {
      tagNamePreference: {
        augments: 'extends',
        constant: 'const',
        fileoverview: 'file',
        returns: 'return'
      }
    }
}
```

Take the following file: 

```typescript
/**
 * @file Katas - tribonacci
 * @module katas/tribonacci
 */

/**
 * Given a starting sequence, `[a, b, c]`, the function returns an array with
 * the first `n` elements of the sequence.
 *
 * @see https://codewars.com/kata/556deca17c58da83c00002db
 *
 * @example tribonacci([1, 1, 1], 10) => [1, 1, 1, 3, 5, 9, 17, 31, 57, 105]
 * @example tribonacci([0, 0, 1], 10) => [0, 0, 1, 1, 2, 4, 7, 13, 24, 44]
 *
 * @param {[number, number, number]} args - Starting sequence
 * @param {number} n - Total number of elements in sequence
 * @return {number[]} First `n` elements of sequence
 */
const tribonacci = (
  [a, b, c]: [number, number, number],
  n: number
): number[] => {
  // Base case: If n is less than or equal to zero, return empty array
  if (n <= 0) return []

  /** @const {number} sum - Sum of {@link a}, {@link b}, and {@link c} */
  const sum: number = a + b + c

  // Generate and return sequence
  return [a, ...tribonacci([b, c, sum], n - 1)]
}

export default tribonacci
```

After running `eslint ./src/katas/tribonacci.ts --exit-on-fatal-error --report-unused-disable-directives --fix`:

```zsh
/Users/lex/Projects/UNICORNWARE/katas/src/katas/tribonacci.ts
  17:11  error  Insert `s`                                                                       prettier/prettier
  26:12  error  Insert `tan`                                                                     prettier/prettier

✖ 8 problems (8 errors, 0 warnings)
  8 errors and 0 warnings potentially fixable with the `--fix` option.
```

- `17:11`: the plugin wants me to use `@returns` => my settings dictate using `@return`
- `26:12`: the plugin wants me to use `@constant` => my settings dictate using `@const`

[1]: https://github.com/gajus/eslint-plugin-jsdoc
[2]: https://github.com/eslint/eslint
[3]: https://github.com/gajus/eslint-plugin-jsdoc#alias-preference
[4]: https://github.com/prettier/prettier-vscode

**Comment by hosseinmd** [comment]
My suggestion is, don't use `eslint-plugin-jsdoc` and `prettier-plugin-jsdoc` both.

**Comment by unicornware** [comment]
@hosseinmd 

given #161, i’ve already removed the prettier plugin.  
that’s not _really_ a solution in my book, however, nor does it sound like it be one for folks **_already_** not using `eslint-plugin-jsdoc`.

**Comment by hosseinmd** [comment]
This is our synonyms https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/4c0b2f6fead8911f0f316361af426087d346ea66/src/roles.ts#L48

**Comment by unicornware** [comment]
@hosseinmd 

if this is the case, it doesn't make sense to me why this plugin doesn't work with `eslint-plugin-jsdoc`, which makes this seem like more of a bug.

how does this library determine a tag is valid? are the keys of `TAGS_SYNONYMS` included in that validation?

**Comment by hosseinmd** [comment]
The main aim of synonyms is creating a standard for tags name, I don't want to create option for this, you should move to this standard because of consistency between packages. Maybe these synonyms don't have a reason, but used in many packages, we want to have a consistency between packages.

**Comment by turadg** [comment]
> we want to have a consistency between packages

Please don't make that a goal of this project. Its main value is consistency _within a codebase_ and making it inflexible makes it harder to adopt into codebases. The default settings suffice to nudge people towards your chosen norms.

**Comment by hosseinmd** [comment]
> Please don't make that a goal of this project. Its main value is consistency _within a codebase_ and making it inflexible makes it harder to adopt into codebases. The default settings suffice to nudge people towards your chosen norms.

Yes you are totaly right. but implemention is hard, some logic was hard code,
