### ISSUE TITLE
Proposal: Balanced lines with TeX's line wrapping algorithm

### ISSUE THREAD

**Issue by egilll** [hosseinmd/prettier-plugin-jsdoc#166]
Hi. At [github.com/egilll/prettier-plugin-jsdoc-balanced](https://github.com/egilll/prettier-plugin-jsdoc-balanced) I've made the plugin use TeX's line wrapping algorithm, which results in more balanced paragraphs.

Current line wrapping:

```
/**
 * By far the biggest reason for adopting Prettier is to stop all the on-going
 * debates over styles. It is generally accepted that having a common style
 * guide is valuable for a project and team but getting there is a very painful
 * and unrewarding process.
 *
 * With Prettier editor integration, you can just press that magic key binding
 * and poof, the code is formatted.
 */
```

With TeX's line wrapping:

```
/**
 * By far the biggest reason for adopting Prettier is to stop all
 * the on-going debates over styles. It is generally accepted that
 * having a common style guide is valuable for a project and team
 * but getting there is a very painful and unrewarding process.
 * 
 * With Prettier editor integration, you can just press
 * that magic key binding and poof, the code is formatted.
 */
```

I find the output to be much more aesthetically pleasing, and wanted to ask whether you'd be interested in a pull request for this functionality.

Some points:
* Currently the code balances each paragraph separately (the blocks above have different widths). I would have to make it take the entire comment block into consideration.
* It currently respects newlines after periods and colons, which I found to be more in line with my expectations (as some comments do not separate paragraphs with two newlines).

**Comment by hosseinmd** [comment]
I like it, but maybe someone doesn't. Could you add an option to disable it? Please PR.

**Comment by egilll** [comment]
Thank you, I'm still working out some kinks in my implementation but will PR when it's ready, closing in the meantime.
