### ISSUE TITLE
Typescript 4.7 syntax error on Instantiation Expressions

### ISSUE THREAD

**Issue by chrisui** [hosseinmd/prettier-plugin-jsdoc#171]
## Repro

https://github.com/chrisui/prettier-repros

```
npm ci
npx prettier index.ts
```

```
SyntaxError: Unexpected token (2:1)
  1 | const okStr = ok<string>
> 2 | const errnum = error<number>
    | ^
```

_See original bug report in prettier/prettier https://github.com/prettier/prettier/issues/13225_

**Comment by hosseinmd** [comment]
This is not

**Comment by chrisui** [comment]
@hosseinmd Can we please re-open this? I've shown in the linked repro and issue that the issue only occurs when this plugin is used. 

What is the issue if it is not this plugin?

**Comment by hosseinmd** [comment]
You have syntax error.
"ok" and "error" are function, they aren't type, we could add generic to function just when calling them, but for your use case change your code to this

```
type OkType = typeof ok;
type ErrorType = typeof error

const okStr: OkType<string> = ok
const errnum: ErrorType<number> = error
```
