### ISSUE TITLE
markdown lists are squashed

### ISSUE THREAD

**Issue by wmertens** [hosseinmd/prettier-plugin-jsdoc#189]
I have `"jsdocExperimentalFormatCommentsWithoutTags": true`.

```
/**
 * Foo
 *
 * - hi
 * - there.
 */
```

becomes
```
/**
 * Foo
 *
 * - hi - there.
 */
```

Would it be possible to retain the markdown formatting?

Thanks once again for your awesome plugin :heart:

**Comment by hosseinmd** [comment]
[prettier-plugin-jsdoc](https://github.com/hosseinmd/prettier-plugin-jsdoc) full supported jsdoc module
you don't need to add jsdocExperimentalFormatCommentsWithoutTags 

Make sure you installed right plugin
