### ISSUE TITLE
Some reason prettier adds spaces in example section

### ISSUE THREAD

**Issue by 5saviahv** [hosseinmd/prettier-plugin-jsdoc#19]
Some reason prettier adds spaces in javascript examples each time I press save in vscode. I tried with cli but same.
if I specified `"jsdocParser": false` this behaviour stops so I believe it comes from this package.

Some reason it also wont respect **print width** setting.

``` js
/**
...
 * @example <caption>with selector</caption>
 *   const $ = ccashio.test(`
 *     <div id=test>
 *       <p>Hello</p>
 *       <b><p>World</p></b>
 *     </div>
 *   `);
...
*/
```
one idea was maybe it is somehow markdown related and escaped **\`** with **\\\`**, but then behaviour changes to adding new lines.

**Comment by hosseinmd** [comment]
Fixed in v0.3.4

Thank you.
