### ISSUE TITLE
Add parentheses around union types

### ISSUE THREAD

**Issue by yoriiis** [hosseinmd/prettier-plugin-jsdoc#190]
First, thanks for the plugin!

JSDoc seems to enforce the use of parentheses around several types, however the plugin removes them. Can we change this or add an option to customize the behavior? Thanks

**Before**
```js
/**
 * @param {('open' | 'close')} action Action type
 */
export default function sampleFunction(action) {}
```

**After**
```js
/**
 * @param {'open' | 'close'} action Action type
 */
export default function sampleFunction(action) {}
```

Resources:
- https://jsdoc.app/tags-param.html#multiple-types-and-repeatable-parameters
- https://github.com/jsdoc/jsdoc/issues/1104
- https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System

**Comment by hosseinmd** [comment]
Jsdoc don't force you to use/not-use parentheses. Removing parentheses is prettier behavior for multiple type. For example, if you define a type like that in a typescript file, prettier will be remove parentheses.
