### ISSUE TITLE
Support Prettier 3.0.0

### ISSUE THREAD

**Issue by melink14** [hosseinmd/prettier-plugin-jsdoc#194]
Two problems I saw so far:

First, I had to specify the full path to the module in order to add the plugin: 
`plugins: ['./node_modules/prettier-plugin-jsdoc/dist/index.js'],`

Second, after that some objects were undefined (probably due to new async API?)
```
Error:  Cannot read properties of undefined (reading 'filter')
Error: Process completed with exit code 1.
```

I guess we can follow the migration guide here: https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F

It would definitely require a new major version since it seems that it might be hard for new plugins to support old prettier...

**Comment by acarstoiu** [comment]
This one costed me more than one hour, thought I was fighting other problems.

Why is the peer dependency specified like **[this](https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/afd080bebd4e5d485d61e184c1e921c6aca81f09/package.json#L70)** ❓❗
