### ISSUE TITLE
Add support for prettier 3.0

### ISSUE THREAD

**Issue by curthipster** [hosseinmd/prettier-plugin-jsdoc#196]
prettier fails with error after upgrading from 2.8.8 to 3.0.0:

```
> prettier . --check

Checking formatting...
[error] Cannot read properties of undefined (reading 'filter')
```

In case it helps, `prettier-plugin-tailwindcss` had a similar [issue](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/176#issuecomment-1621926950).

**Comment by yf-yang** [comment]
Seems #195 is the WIP

**Comment by auvred** [comment]
Duplicate of https://github.com/hosseinmd/prettier-plugin-jsdoc/issues/194

**Comment by hosseinmd** [comment]
Fixed https://github.com/hosseinmd/prettier-plugin-jsdoc/pull/195

**Comment by curthipster** [comment]
Oh, thank you and sorry for the noise. I swear I searched but apparently didn't look hard enough.
