### ISSUE TITLE
Don't capitalize @example code

### ISSUE THREAD

**Issue by plehnen** [hosseinmd/prettier-plugin-jsdoc#198]
It capitalizes code which is not correct.

Before:
`@example cy.dataCy('greeting')`

After:
`@example Cy.dataCy('greeting')`

**Comment by hosseinmd** [comment]
this example is not correct as jsdoc document change it to this

@example description
   cy.dataCy('greeting')

**Comment by hosseinmd** [comment]
Description is optional
