### ISSUE TITLE
Parsing error when running prettier

### ISSUE THREAD

**Issue by radomskip** [hosseinmd/prettier-plugin-jsdoc#2]
Hi, when I execute prettier on this file:

<img width="756" alt="Captura de Pantalla 2020-06-30 a la(s) 11 03 55" src="https://user-images.githubusercontent.com/33379686/86135608-730e6880-bac1-11ea-8f6f-39c78a2eab4b.png">

I get this error:

<img width="763" alt="Captura de Pantalla 2020-06-30 a la(s) 10 55 37" src="https://user-images.githubusercontent.com/33379686/86135399-23c83800-bac1-11ea-867c-e75a0bee7bc3.png">

If I remove  <<?>> (optional character) the error disappears, but then this other error occurs:

<img width="585" alt="Captura de Pantalla 2020-06-30 a la(s) 11 23 39" src="https://user-images.githubusercontent.com/33379686/86137959-35f7a580-bac4-11ea-83ea-40fbaf9a77cb.png">

I share this repository so you can clone and verify:

https://github.com/radomskip/test-jsdoc

**Comment by hosseinmd** [comment]
This error is not about JsDoc. This error occurs because your type definition is wrong.

I think you can solve the problem with this code
```js
import * as React from "react";

import "@tiendanube/styles/css/Text.css";

export type InterfaceText = {
  /** Text to be displayed dsfs v f sdf sdsd asd d */
  children: React.ReactText,
  /** Size */
  size?: "regular",
  /** Type of react mouse event onclick to manage event click and void return */
  onClickPrimary?: (
    event: React.MouseEvent<HTMLButtonElement, MouseEvent>,
  ) => void,
};
/** @param {InterfaceText} props */
function Text({ children, size = "regular" }: InterfaceText): JSX.Element {
  return <p className={`nimbus--text nimbus--text_${size}`}>{children}</p>;
}

export default React.memo(Text);
```

**Comment by hosseinmd** [comment]
Or if you want to use jsdoc in your type definition this can help you.

```js

import * as React from "react";

import "@tiendanube/styles/css/Text.css";

/**
 * @typedef {object} InterfaceText
 * @property {React.ReactText} children Text to be displayed dsfs v f sdf sdsd asd
 * @property {"regular"} size Size
 * @property {(event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void} onClickPrimary Type of react mouse
 *     event onclick to manage event click and void return
 */

/**
 * @param {InterfaceText} props
 * @returns {JSX.Element}
 */
function Text({ children, size = "regular" }) {
  return <p className={`nimbus--text nimbus--text_${size}`}>{children}</p>;
}

export default React.memo(Text);
```

**Comment by hosseinmd** [comment]
Fixed in this https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/c98ecbb44c1eeb462a7fd632fd7d9449df717fb7
