### ISSUE TITLE
Formatting issue with `@remarks` tag when using list items

### ISSUE THREAD

**Issue by Gykonik** [hosseinmd/prettier-plugin-jsdoc#201]
The output is improperly indented when formatting comments with the `@remarks` tag and using list items. Instead of preserving the original list format, additional indentation is included.

Example:
```
/**
 * Just a simple test
 *
 * @remarks
 *   - Remark 1
 *   - Remark 2
 *   - Remark 3
 */
```

Formatted Result:
```
/**
 * Just a simple test
 *
 * @remarks
 *   - Remark 1
 * 
 *       - Remark 2
 *       - Remark 3
 */

```
I'm unsure whether my configurations are off, or this is a bug. My configurations are as follows:
```
"options": {
  "jsdocSeparateTagGroups": true,
  "tsdoc": true
}
```

**Comment by hosseinmd** [comment]
Release v1.0.2
