### ISSUE TITLE
The plugin does not work if it is not listed last in the list of plugins.

### ISSUE THREAD

**Issue by ManucherKM** [hosseinmd/prettier-plugin-jsdoc#212]
Hello. I recently came across a problem. For some unknown reason, the plugin stops working if it is not listed last in the list of plugins.
Config in which it does not work:
![image](https://github.com/hosseinmd/prettier-plugin-jsdoc/assets/91463158/4bf50673-3c4c-4bfb-8d60-a255380576af)
The config in which it works:
![image](https://github.com/hosseinmd/prettier-plugin-jsdoc/assets/91463158/4baa4d7e-cab3-47ec-8bc9-616b405c9e7a)
Prettier and plugins for it are in my package.json:
![image](https://github.com/hosseinmd/prettier-plugin-jsdoc/assets/91463158/3c28da04-1024-4ba5-9ff2-de5596d0d0dc)
I apologize for showing the config with screenshots. When I submit my code, GitHub can't format it correctly.

**Comment by hosseinmd** [comment]
Hi dear, 
Related to https://github.com/hosseinmd/prettier-plugin-jsdoc/issues/99
We fixed https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/bfc9c3901e6a0d702b740e9297dea6d5606f3623

**Comment by shnhrrsn** [comment]
I don't think this is fixed, I just installed `prettier-plugin-jsdoc` for the first time, so using latest version, and couldn't figure out why it wasn't doing anything until I found this issue.

Moving `prettier-plugin-jsdoc` to the end of my plugins "fixed" the issue.

**Comment by hosseinmd** [comment]
Perhaps this should be fixed by prettier. Prettier doesn't have an official way to these types of plugins.
