### ISSUE TITLE
Configure camel case annotation

### ISSUE THREAD

**Issue by mrvisser** [hosseinmd/prettier-plugin-jsdoc#23]
Hey, love the plugin. Thanks @hosseinmd and @gum3n.

I'm working with TSOA, which runs heavy on some JSDoc annotations, and they rely on one: @tsoaModel which is a camel/mixed case annotation.

Unfortunately, this library lower-cases it, resulting in breaking that functionality. It's not compatible.

Would it make sense to only lower-case standard JSDoc annotations, and leave unknown ones be? Happy to try and contribute this if we think it's the way forward.

**Comment by hosseinmd** [comment]
i agree. Contribute is so welcome. Please PR.
