### ISSUE TITLE
disable semi only in jsdoc

### ISSUE THREAD

**Issue by eduardocque** [hosseinmd/prettier-plugin-jsdoc#232]
Hi, is there a way to disable semicolon only in jsdoc ?

im trying to use this plugin but when im running jsdoc is crashing with this error
```
ERROR: Unable to parse a tag's type expression for source file xxx.js in line 24 with tag title "param" and text "{{
  children: React.ReactNode;
  value: any;
}} props": Invalid type expression "{
  children: React.ReactNode;
  value: any;
}": Expected "!", "#", "$", "(", ",", "-", ".", "/", "0", ":", "<", "=", "?", "@", "[]", "\\", "_", "|", "}", "~", "‌", "‍", Unicode combining mark, Unicode decimal number, Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode punctuation connector, Unicode titlecase letter, Unicode uppercase letter, or [1-9] but ";" found.
```

```
/**
 * @param {{
 *   children: React.ReactNode;
 *   value: any;
 * }} props
 * @returns {React.ReactElement}
 */
 ```

should be
```
/**
 * @param {{
 *   children: React.ReactNode,
 *   value: any
 * }} props
 * @returns {React.ReactElement}
 */
```

**Comment by hosseinmd** [comment]
It is because of typescript, I can't change it.
Which package is crashing?

**Comment by eduardocque** [comment]
@hosseinmd `jsdoc` fails, noticed that the normal prettier with `semi` is trying to put `;` everywhere like the example and should be `,` like the second example, when is the second example `jsdoc` works well

**Comment by hosseinmd** [comment]
I know, but the code into curly brackets is type and formatted as typescript code.

**Comment by hosseinmd** [comment]
```
/**
 * @param {here is type} props
 */
 ```

**Comment by eduardocque** [comment]
what can i do in that case ? im trying to autogenerate docs with jsdoc ?

**Comment by hosseinmd** [comment]
I hope jsdoc could fix it. Create an issue in jsdoc repo, and I will follow up too.

**Comment by dmnsgn** [comment]
Was there any issue opened on jsdoc repo or a workaround here?

Only way I could make it work was using the dot notation:

```js
/**
 * @param {object} props
 * @param {string} props.one
 * @param {string} props.two
 * @param {number} [props.three=3]
 * @returns {string}
 */
```
