### ISSUE TITLE
Word wrap does not account for tabs

### ISSUE THREAD

**Issue by RunDevelopment** [hosseinmd/prettier-plugin-jsdoc#25]
![image](https://user-images.githubusercontent.com/20878432/106390986-66e9e100-63eb-11eb-9e34-62e1dc6d0a33.png)

I did a little digging in the code and it seems that one tab is treated the same as one space. Obviously, this is a problem.

---

Print width is configured as 120. The column ruler sits at 120 as well. Tabs are configured to be 4 spaces wide (in both Prettier and my IDE).

**Comment by hosseinmd** [comment]
Could you give me your example code?

**Comment by RunDevelopment** [comment]
[Source](https://github.com/PrismJS/prism/blob/266cc7002e54dae674817ab06a02c2c15ed64a6f/components/prism-core.js#L286).

**Comment by hosseinmd** [comment]
i added your prism source to examples 
https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/ccf2028a0f26829df94213819630e4b2c3145c93
prettier converted tabs to spaces, and every thing work well

**Comment by RunDevelopment** [comment]
> prettier converted tabs to spaces, and everything work well.

Yes, but Prism doesn't use spaces. We use tabs and with tabs, the print width is calculated incorrectly.

**Comment by hosseinmd** [comment]
So please add your options to  https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/master/tests/filePrism.test.js#L22
