### ISSUE TITLE
Tag sorting breaks type definitions

### ISSUE THREAD

**Issue by RunDevelopment** [hosseinmd/prettier-plugin-jsdoc#29]
TypeScript's JS check supports multiple type definitions per comment. This plugins breaks those:

### Example

Before:
```js
	/**
	 * @callback ClassMapper
	 * @param {string} className
	 * @param {string} language
	 * @returns {string}
	 *
	 * @callback ClassAdder
	 * @param {ClassAdderEnvironment} env
	 * @returns {undefined | string | string[]}
	 *
	 * @typedef ClassAdderEnvironment
	 * @property {string} language
	 * @property {string} type
	 * @property {string} content
	 */
```

After:
```js
	/**
	 * @typedef ClassAdderEnvironment
	 * @callback ClassMapper
	 * @callback ClassAdder
	 * @property {string} language
	 * @property {string} type
	 * @property {string} content
	 * @param {string} className
	 * @param {string} language
	 * @param {ClassAdderEnvironment} env
	 * @returns {string}
	 * @returns {undefined | string | string[]}
	 */
```

**Comment by danielpza** [comment]
We could define a series of task that work like regions, eg `@callback` and `@typedef`. When one is encountered we limit the sorting to right before it, and start a new region to sort after it.

**Comment by RunDevelopment** [comment]
This will work but has a problem: `@template`.

Let's look at the following:

```js
/**
 * @template T
 * @typedef {T | number} Foo1
 * @typedef {T | number} Foo2
 * @typedef {T | number} Foo3
 */
```

![image](https://user-images.githubusercontent.com/20878432/106475481-429f0a80-64a6-11eb-939f-ba1b4358284d.png)
![image](https://user-images.githubusercontent.com/20878432/106475500-47fc5500-64a6-11eb-9b2d-1f01cac42d12.png)
![image](https://user-images.githubusercontent.com/20878432/106475528-4f236300-64a6-11eb-9d5d-2c366d84a3d3.png)

This one is even worst:

```js
/**
 * @template T
 * @param {T} a
 * @returns {void}
 * 
 * @typedef {number} Foo
 */
function name(a) {}
```

![image](https://user-images.githubusercontent.com/20878432/106475785-a0cbed80-64a6-11eb-86dc-a907ebc3c63f.png)
![image](https://user-images.githubusercontent.com/20878432/106475806-a88b9200-64a6-11eb-8d2f-7e4270d948ff.png)

The position of `@template` doesn't matter in both cases. I honestly don't know how to best handle this situation.

**Comment by danielpza** [comment]
For one we could disable sorting if we encounter any typescript related tags. Perhaps we can do this until we find a better solution...

**Comment by RunDevelopment** [comment]
Sounds like a good solution for now.

**Comment by RunDevelopment** [comment]
I also found this:

Before:
```js
/**
 * A function which will invoked after an element was successfully highlighted.
 *
 * @callback HighlightCallback
 * @param {Element} element The element successfully highlighted.
 * @returns {void}
 * @global
 * @public
 */
```
![image](https://user-images.githubusercontent.com/20878432/106650845-ab17e580-6593-11eb-8e22-df4f0ad73a44.png)


After:
```js
/**
 * A function which will invoked after an element was successfully highlighted.
 *
 * @callback HighlightCallback
 * @param {Element} element The element successfully highlighted.
 * @global
 * @public
 * @returns {void}
 */
```

![image](https://user-images.githubusercontent.com/20878432/106650808-a2271400-6593-11eb-9a64-63d8904fb5ce.png)
