### ISSUE TITLE
Initial source code

### ISSUE THREAD

**Issue by gum3n** [hosseinmd/prettier-plugin-jsdoc#3]
Well You could at least mention from where you got the initial source code
https://gitlab.com/gumen/prettier-plugin-jsdoc

**Comment by wwalasekperform** [comment]
Also, our code is still in there and you claimed copyright https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/2b89423324e0234ff628bf8d01a2dafdc893d9e5/LICENSE#L3 - fork would be more appropriate. This is not what opensource is for

**Comment by gum3n** [comment]
To be perfectly clear. It's fantastic that you are developing this project. You have put it on npm, and there are people that use it :heart: 

I just don't quite get your motives behind getting all the credit for yourself. It's open source. We [code together](https://www.youtube.com/watch?v=_9aLiv5M6AQ) :wink:

**Comment by hosseinmd** [comment]
Yes, you are right.
I started this module from your module. many things have changed. 

Your project doesn't have a license and i have to set up a license in that for publishing project on npm, there is an MIT license. this project is completely open source too.

i will mention you on that.

**Comment by hosseinmd** [comment]
https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/f209561df4fc45c38f235f908b59487806a03698
