### ISSUE TITLE
Incorrect Array type transformation

### ISSUE THREAD

**Issue by RunDevelopment** [hosseinmd/prettier-plugin-jsdoc#30]
This plugin tries to transform `Array<T>` to `T[]` but it produces an invalid type if `T` is a lambda.

It's [this regex](https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/8b5a13ad50452deb0d0172e60f490dc2d73d0d78/src/utils.ts#L7)'s fault.

Also, free code review :) [The negated lookaheads](https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/8b5a13ad50452deb0d0172e60f490dc2d73d0d78/src/utils.ts#L7-L8) will always accept and do not change the regex. They can be removed.

### Example

Before:
```js
	/**
	 * @type {Array<(element: HTMLElement) => boolean>}
	 */
	var filters = [];
```

After:
```js
	/** @type {(element: HTMLElement) =[] boolean>} */
	var filters = [];
```

**Comment by hosseinmd** [comment]
Fixed: https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/3aab697d8a78cd72633d39a0b3403d773d0a7ece
