### ISSUE TITLE
Inconsistent tag sorting

### ISSUE THREAD

**Issue by RunDevelopment** [hosseinmd/prettier-plugin-jsdoc#31]
When and in what order are tags sorted?

I have noticed that `@template` tags are sometimes moved before all other tags (like `@param`) but only sometimes. Is this a bug or is this intended behaviour?

**Comment by hosseinmd** [comment]
No that is not correct behavior. `@template` should be on top of `@param`.

**Comment by hosseinmd** [comment]
Could you give me an example

**Comment by RunDevelopment** [comment]
Sure!

### Example

Before:
```js
		/**
		 * Creates a deep clone of the given object.
		 *
		 * The main intended use of this function is to clone language definitions.
		 *
		 * @param {T} o
		 * @param {Record<number, any>} [visited]
		 * @returns {T}
		 * @template T
		 */
```

After:
```js
			/**
			 * Creates a deep clone of the given object.
			 *
			 * The main intended use of this function is to clone language definitions.
			 *
			 * @template T
			 * @param {T} o
			 * @param {Record<number, any>} [visited]
			 * @returns {T}
			 */
```

**Comment by hosseinmd** [comment]
This is correct.

**Comment by hosseinmd** [comment]
Tags order is there https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/master/src/roles.ts#L121

**Comment by RunDevelopment** [comment]
I am truly sorry. It seems like I have accidentally looked at files that were not formatted by prettier regarding the `@template` tag.

**Comment by RunDevelopment** [comment]
So the order is intentionally not alphabetical. Thank you for the info.
