### ISSUE TITLE
Stable tag sorting

### ISSUE THREAD

**Issue by RunDevelopment** [hosseinmd/prettier-plugin-jsdoc#39]
Tag sorting currently uses [`Array.prototype.sort`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort). This sort function is only guaranteed to be stable since quite recently. However, the [current tag sorting](https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/9bb4ec6478529c7f2e89e35e18c48ff8181b65df/src/parser.ts#L169) assumes stable sorting and may randomly reorder tag (e.g. `@param` tags).

Either specify that NodeJS >=12.0.0 is required or use a [stable sort function](https://www.npmjs.com/package/stable).

**Comment by hosseinmd** [comment]
I think we don't have to pay for the previous versions, users can update NodeJS to the latest version.

> Either specify that NodeJS >=12.0.0 is required 

Is good solution
