### ISSUE TITLE
Should wrap at 80 columns or be configurable

### ISSUE THREAD

**Issue by melink14** [hosseinmd/prettier-plugin-jsdoc#4]
Currently, it seems to wrap based on the length of the comment ignoring the spaces and *s before the start of a jsdoc line.

This means that it wraps at the odd length of 83 characters for a standard jsdoc setup.

The forked module had a `jsdocPrintWidth` option that could be used to account for that difference but it seems this version removed it.

**Comment by hosseinmd** [comment]
You are right, I removed jsdocPrintWidth but instead used prettier printWidth options, for more matching with prettier.
About 83 characters, I have another situation where using jsdoc in class, here jsdoc has more than 83 characters maybe 85. 
Imagine where using comment more deep. If I don't ignore space the real length of comment is less.
This needs discussion. What can I do?
1- continue current
2- Don't ignore the starting spaces

**Comment by melink14** [comment]
Ah, that makes sense and I agree that matching with prettier's printWidth is correct.

You're right that at deeper levels the indentation increases though I don't think it will go too much deeper than that in a clean codebase!

To that end, I vote for #2 since that will allow the comments to align with the code. Since code is even more likely to be nested than JSDoc it seems like as long as the code is readable, the JSDoc should also be readable!

Thanks again for your work!

**Comment by hosseinmd** [comment]
Ok, I will do that tonight.

**Comment by hosseinmd** [comment]
Done

**Comment by melink14** [comment]
Thanks for the fast response! Cheers!
