### ISSUE TITLE
Examples code, code blocks, and types use tab indentation

### ISSUE THREAD

**Issue by RunDevelopment** [hosseinmd/prettier-plugin-jsdoc#47]
If the option `useTabs: true` is active, example code, MD code blocks, and types (the types of tags if multiline) will be indented using tabs. This looks very weird as everything else inside JSDoc comments is usually indented using spaces.

This is especially noticeable in `@example` tags because the code as a whole is indented by 2 spaces and tabs after the space indentation look quite silly.

Is this intentional? Should spaces be used instead?

**Comment by hosseinmd** [comment]
I think we could get spaces number from prettier options. What you think?

**Comment by RunDevelopment** [comment]
"We" (as in this plugin) doesn't do the indentation. I was talking about the indentation of embedded code "we" (as in this plugin) uses Prettier to format.

Example:

![image](https://user-images.githubusercontent.com/20878432/106888474-e37c0880-66e6-11eb-8bbe-d3118827e65b.png)

This issue is about whether the tabs in embedded code are intentional or whether this should be classified as a bug.

**Comment by hosseinmd** [comment]
Excuse me about my misunderstanding, yes that is true behavior. 
For types, example and code block we used prettier to format. Because of that prettier used tab instead of space. 
I think we should not ignore it.

**Comment by hosseinmd** [comment]
We have not paid any attention to it. for example, when adding indented to description.

**Comment by RunDevelopment** [comment]
![image](https://user-images.githubusercontent.com/20878432/106897655-83d82a00-66f3-11eb-8811-235c4f7755e7.png)

Currently, cases like this are possible where a tab is displayed with the same width as a single space. 

> I think we should not ignore it.

I think that it might be better to override the configured behaviour and use spaces. 

If not for code blocks and examples, at least for types. Types are usually not explicitly formatted by users, so it should be fine for us to use whatever indentation type we want.

**Comment by hosseinmd** [comment]
IMO that is better to use prettier options for this plugin. Like `printwidth`.

**Comment by RunDevelopment** [comment]
Yes, I meant to suggest that we do use Prettier's options. The only option we would override is the `useTabs` options. All else would be unchanged.

**Comment by hosseinmd** [comment]
https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/8d96fd710c3c492494e7e44836eb16d07acebd1c

**Comment by RunDevelopment** [comment]
> This issue is about whether the tabs in embedded code are intentional or whether this should be classified as a bug.

8d96fd710c3c492494e7e44836eb16d07acebd1c did not address this.
