### ISSUE TITLE
Support for Windows line breaks (CRLF)?

### ISSUE THREAD

**Issue by RunDevelopment** [hosseinmd/prettier-plugin-jsdoc#48]
Does this plugin support Windows line breaks (CRLF)? It seems like most of the code assumes Unix line breaks. Is this intentional?

**Comment by hosseinmd** [comment]
This need to implement.

**Comment by RunDevelopment** [comment]
Shall I make a PR?

**Comment by hosseinmd** [comment]
Yes please.
