### ISSUE TITLE
Tag order: Tags between `@param` and `@returns`

### ISSUE THREAD

**Issue by RunDevelopment** [hosseinmd/prettier-plugin-jsdoc#49]
Right now, there can be [a lot of stuff](https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/d34af57c59ccee880862f8fc36582f540e71acc6/src/roles.ts#L151) between `@param` and `@return` tags. Why?

**Comment by hosseinmd** [comment]
Almost always throws, yields and returns are last tags. 
Which tag is the problem for you?

**Comment by RunDevelopment** [comment]
Well, except for maybe `@throws` and `@yields`, all of them. The biggest problem is "other". Why are all unknown tags inserted between a function's parameters and its return type? That's the biggest problem but `@see` isn't much better.

I would argue that there shouldn't be anything in between `@param` and `@returns`. 

IMO, `@throws` should be after `@returns` too. For JavaDoc, there is an official style guide and that defines the [tag order](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html#orderoftags) with `@exception` (same as `@throws` in JSDoc) being after `@return`.
(`@yields` and `@returns` are mutually exclusive, so the order of the two doesn't matter.)

**Comment by hosseinmd** [comment]
What orders you suggested?
Please add your other tags too.

**Comment by RunDevelopment** [comment]
How about this?

```js
const TAGS_ORDER = [
  // no changes before
  TEMPLATE,
  FUNCTION,
  CLASS,
  EXTENDS,
  MEMBER,
  TYPEDEF,
  TYPE,
  PROPERTY,
  CALLBACK,
  PARAM,
  YIELDS,
  RETURNS,
  THROWS,
  "other",
  SEE,
  TODO,
]
```

([Current](https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/d34af57c59ccee880862f8fc36582f540e71acc6/src/roles.ts#L122))

**Comment by hosseinmd** [comment]
Looks good to me, please make a PR.
