### ISSUE TITLE
Tag order doesn't work

### ISSUE THREAD

**Issue by RunDevelopment** [hosseinmd/prettier-plugin-jsdoc#54]
Tag order doesn't work in [this test file](https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/422047192e63a72e6c61dcbcb0074070713c8ab2/tests/__snapshots__/template.test.js.snap#L7) as discussed [here](https://github.com/hosseinmd/prettier-plugin-jsdoc/pull/52#discussion_r570265261).

**Comment by hosseinmd** [comment]
fixed: https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/13318611b9706f0b8f40c5c98172eb231243dc2c
