### ISSUE TITLE
Incorrectly calculated print width if comment indentation changes

### ISSUE THREAD

**Issue by RunDevelopment** [hosseinmd/prettier-plugin-jsdoc#58]
Right now, the comment indentation is calculated by counting tabs and spaces in the original text. This means that the calculated indentation will only be correct if the indentation of the comment does not change.

This problem can be seen in prism-core.js. All comments gain an additional indentation level which means that the indentation will be calculated incorrectly and the print width will be too big (4 chars too big).

To work around this issue, users can format their files twice. This issue only occurs if the indentation of a comment changes and the comment contains text that has to be wrapped.

(For more information, see #56.)

**Comment by hosseinmd** [comment]
Maybe https://prettier.io/docs/en/plugins.html#printers could help

**Comment by hosseinmd** [comment]
But I don't know can help, we should test
