### ISSUE TITLE
[0.1.1] Formatting differences => bugs?

### ISSUE THREAD

**Issue by melink14** [hosseinmd/prettier-plugin-jsdoc#6]
Noticed some surprising results in the latest version of the formatter. Thanks as always for taking a look.
I know you made a change that allowed indentation for lists but not sure if the other changes were intended.

```
 * Retrieves saved options from chrome.storage.sync and populates form
 * elements.
```

becomes

```
/**
 * Retrieves saved options from chrome.storage.sync and populates form elements.
```

even though the second example is 81 characters long. (This may be intentional but 

```
  /**
   * Transforms data
   *
   * @override
   */
  _transform(data: Buffer, encoding: string, callback: TransformCallback) {
```

became

```
  /**
 * Transforms data
 * 
 * @override 

 */
  _transform(data: Buffer, encoding: string, callback: TransformCallback) {
```

For some reason, the asterisks are now inbetween the two spaces. (I noticed because eslint `no-trailing-spaces` triggered. on dependabot auto-update.)

**Comment by hosseinmd** [comment]
Fixed: https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/b4fa77e5b897d110a00beb7c6d550e346aa95733
v0.1.2

**Comment by hosseinmd** [comment]
Please test the latest version and feel free to reopen if there is still a problem.

**Comment by melink14** [comment]
Thanks for the update! The main problem with `@override` was fixe but the first example of a line unwrapping to 81 columns is still there.

If I add one more character it re-wraps so it seems like an off by one error. I can open a new issue for that though if you want to keep this one about @override.

Thanks!

**Comment by hosseinmd** [comment]
Something is wrong with that. So I test that line  it seem to have 80 char
<img width="608" alt="Screen Shot 2020-09-03 at 11 27 44 AM" src="https://user-images.githubusercontent.com/45505767/92081746-cb6f2880-edd8-11ea-87b7-2401b24e2773.png">

**Comment by melink14** [comment]
Ah, I think I know what's going on.

In reality, there's always a newline character at the end of the line so really the IDE is counting it like:
```
" * Retrieves saved options from chrome.storage.sync and populates form elements.\n".length
```

I think the newline character is usually counted for formatters, but it's not big issue to me now that we know the reason why!

**Comment by melink14** [comment]
Let me know if I should file a new issue for not counting newlines or if you want to keep it at code width + 1.

In the latter case, I'll reformat my code and so I can update to the new NPM version. :)

**Comment by hosseinmd** [comment]
Please create a new issue if the problem is not related to this issue.
