### ISSUE TITLE
Sort `@param` tag by the order of occurrence in function if possible

### ISSUE THREAD

**Issue by RunDevelopment** [hosseinmd/prettier-plugin-jsdoc#60]
Try to detect if the current doc comment is the comment of a function declaration/definition and sort all `@param` tags by the order of the referred to parameters in the function.

### Example

Before:
```js
/**
 * @param c
 * @param b
 * @param a
 */
function name(a, b, c) {}
```

Before:
```js
/**
 * @param a
 * @param b
 * @param c
 */
function name(a, b, c) {}
```

**Comment by hosseinmd** [comment]
https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/25244133d1aa23483b6cae2b0319f36d4223da59 

Implemented:
- function
Needed to implement:
- arrow function
- Object/class methods

**Comment by hosseinmd** [comment]
https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/68103434ba7259144e0e6cab0c8af8463df3fc0e

**Comment by hosseinmd** [comment]
I think this is enough for this feature. We can continue to improve this if requested. Thank you for your help.
