### ISSUE TITLE
`@example` code indentation is partially removed even with `jsdocKeepUnParseAbleExampleIndent`

### ISSUE THREAD

**Issue by RunDevelopment** [hosseinmd/prettier-plugin-jsdoc#69]
If example code is indented with spaces, 2 spaces will always be removed even if `jsdocKeepUnParseAbleExampleIndent` is enabled.

This is a bug.

### Example
[Before](https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/4a9cbd2e21ba3be56862adb3e75b86c48a1e329d/tests/files/prism-core.js#L279): indented using 4 spaces
```js
/**
 * @example
 * Prism.languages['css-with-colors'] = Prism.languages.extend('css', {
 *     // Prism.languages.css already has a 'comment' token, so this token will overwrite CSS' 'comment' token
 *     // at its original position
 *     'comment': { ... },
 *     // CSS doesn't have a 'color' token, so this token will be appended
 *     'color': /\b(?:red|green|blue)\b/
 * });
 */
```

[After](https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/4a9cbd2e21ba3be56862adb3e75b86c48a1e329d/tests/__snapshots__/files/prism-core.js.shot#L281): indented using 2 spaces
```js
/**
 * @example
 *   Prism.languages['css-with-colors'] = Prism.languages.extend('css', {
 *     // Prism.languages.css already has a 'comment' token, so this token will overwrite CSS' 'comment' token
 *     // at its original position
 *     'comment': { ... },
 *     // CSS doesn't have a 'color' token, so this token will be appended
 *     'color': /\\\\b(?:red|green|blue)\\\\b/
 *   });
 */
```

The indentation is "after" did not change to 2 spaces. This plugin simply removed 2 spaces from every line that starts with spaces. If the example contained a line indented with 8 spaces, the plugin would change that to 6 spaces.

**Comment by hosseinmd** [comment]
Plugin doesn't change indention just adding 2 space to beginning.
To do that we're removing previse 2 spaces and adding 2 spaces again after format example

**Comment by hosseinmd** [comment]
You can't add indention, prettier doesn't allow you, indention in under prettier control, you don't have any control to indention

**Comment by hosseinmd** [comment]
Your example isn't unparseable

**Comment by hosseinmd** [comment]
About unparse able examples you are right, that is a bug

**Comment by RunDevelopment** [comment]
Yes, this is an unparsable example before of the `'comment': { ... },` line. Kinda hard to see. Sorry about that.
