### ISSUE TITLE
Handle a default import using `{import("Foo")}`

### ISSUE THREAD

**Issue by sgtpep** [hosseinmd/prettier-plugin-jsdoc#7]
At the moment, `@typedef {import("Foo")} Foo` works fine in TypeScript and is equivalent to `@typedef {import("Foo").default} Foo`, but `prettier-plugin-jsdoc` removes a trailing bracket: `@typedef {import("Foo"} Foo`.

**Comment by hosseinmd** [comment]
I fixed that in https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/7fd2a8007bcb483ded0cda22d3761fcb03a7c8e 
The changes will be published on Saturday.
Thanks

**Comment by sgtpep** [comment]
Wow, that was quick! Thank you so much!

**Comment by hosseinmd** [comment]
done v0.2.0
