### ISSUE TITLE
Line column width calculation appears to not include newline leading to 81 character lines

### ISSUE THREAD

**Issue by melink14** [hosseinmd/prettier-plugin-jsdoc#8]
Branched from #6 

```
/**
 * Retrieves saved options from chrome.storage.sync and populates form
 * elements.
 */
```

becomes

```
/**
 * Retrieves saved options from chrome.storage.sync and populates form elements.
 */
```

The key (as discovered in #6) is that the string is 80 characters not including the final `\n` character.

This started in v0.1.1 but I wasn't able to find exactly why from quickly looking at the diffs. (Stil present in v0.2.0).

Most lines aren't exactly 81 characters long so it's definitely an edge case!

If it was an accident then maybe we should fix it in case it surprises people later.

An alternative point is that the exact width doesn't matter as long as it's around the `print-width`. I found this statement of philosophy: https://prettier.io/docs/en/options.html#print-width that mentions that Prettier doesn't treat it as a max but more like an average.

Feel free to close in that case; I was mostly surprised since my lint check failed during upgrade but I can reformat easily to the new standard.

**Comment by hosseinmd** [comment]
https://prettier.io/docs/en/options.html#print-width this is cool. But I don't know how much is average?

**Comment by melink14** [comment]
Hmm, I don't think it cares about a precise average but more like having some lines be shorter and some lines be longer but in general ending up around 80/`printWidth`. I think it's more of a philosohpy.

The implementation can vary. For example, since the newline character does not affect our reading of the code it doesn't make sense to wrap *just* for the newline so we can trim the whitespace before calculating.

Another example that fits the philosophy: allow line to be N characters too long if it means keeping a word on the same line. (Break only at spaces etc)

There are probably more examples for code formatting but the idea is not being super strict.

In this case, I think there's an argument to say that it's better to not count newline but I wanted to post this issue to ensure agreement since it wasn't in the patch notes/commit messages.

**Comment by hosseinmd** [comment]
Right, I think removing newline from count is a good idea. But what about the small word at the end of the line which has 81 char or something?

**Comment by melink14** [comment]
I think if there's a good general purpose rule to encode then it makes sense, otherwise as long as we're consistent, the code will be readable.

For that case, I think it could be implemented like:

`if line > 80 break at first whitespace past 80 unless line is still >= 90`

or similar. But it might be better to keep it simpler unless more users bring up those ideas.

These are the fun problems of software where there's no right or wrong answer. :)

**Comment by hosseinmd** [comment]
Done https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/770e213f3cbf30f4dba0449fb2953c08a05a5bd7
