### ISSUE TITLE
Github actions

### ISSUE THREAD

**Issue by hosseinmd** [hosseinmd/prettier-plugin-jsdoc#82]
This Plugin need GitHub actions for test plugin with various versions of node and prettier.
I don't know anything's about GitHub actions.

@RunDevelopment @danielpza @mrvisser @forivall

**Comment by RunDevelopment** [comment]
I don't know how to do a matrix for prettier versions, but I can add one that tests for multiple NodeJS versions. Want me to make a PR?

**Comment by hosseinmd** [comment]
Yes please.
