### ISSUE TITLE
TSDoc: Support `@example` tag

### ISSUE THREAD

**Issue by RunDevelopment** [hosseinmd/prettier-plugin-jsdoc#86]
The[ `@example` tag in TSDoc](https://tsdoc.org/pages/tags/example/) has a different semantic than in JSDoc.

**Comment by hosseinmd** [comment]
VS Code not supported

**Comment by RunDevelopment** [comment]
@hosseinmd Please reopen.

Just because VSCode doesn't support TSDoc, doesn't mean that this isn't an issue. Static site generators like TypeDoc do correctly support TSDoc's `@example` tag. If this issue isn't resolved, this plugin cannot be used in combination with TypeDoc and other software that implements the TSDoc standard.

**Comment by hosseinmd** [comment]
VS Code user is more than other apps. We will implement it if that doesn't break the example view in VS Code.

**Comment by hosseinmd** [comment]
@example tag in tsdoc in completely different because that is Markdown but jsdoc example is code

**Comment by RunDevelopment** [comment]
Then please add an option to turn off formatting the `@example` tag. Otherwise I can't use this plugin in my TS projects.

**Comment by hosseinmd** [comment]
This not related to typescript, I am a typescript developer I always used typescript, there is no reason your project can't use this plugin. Could you give me what's your project config?

**Comment by RunDevelopment** [comment]
> This not related to typescript

Of course it is related. TSDoc is __the__ documentation standard for TS.

> there is no reason your project can't use this plugin

I already gave you the reason:

"Static site generators like TypeDoc do correctly support TSDoc's `@example` tag. If this issue isn't resolved, this plugin cannot be used in combination with TypeDoc and other software that implements the TSDoc standard."

I use TypeDoc in my projects.

---

But I also want to remind you of [this](https://github.com/hosseinmd/prettier-plugin-jsdoc/discussions/68#discussioncomment-360339). Or is TSDoc isn't going to be supported after all?

**Comment by danielpza** [comment]
how does it break vscode?

**Comment by danielpza** [comment]
We should at least keep it open until vscode fix it on their side. The issue is not out of the scope of the project after all.

**Comment by hosseinmd** [comment]
I think we could add TSDoc to options.

If set true to TSDoc we could do some work like:
 - format examples as Markdown like description
 - Remove type from tags like param (in TSDoc no need to add type)

I don't know other specific rules of TSDoc, I need help about that.
If any own agree we could do it

**Comment by danielpza** [comment]
> Remove type from tags like param (in TSDoc no need to add type)

I don't know about removing the tag, I think it should keep it on TSDoc.

Is it possible to use TSDoc on javascript?, in that case if it is removed they will lose type information

**Comment by hosseinmd** [comment]
I found this commit https://github.com/Linux123123/JSPteroAPI/commit/9efe556cc545766ac4c40f096f2c23a4ee97d967

**Comment by hosseinmd** [comment]
https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/4213aedd3b63e9dbc9e25c2b58a6e3cfcf7ede6b
