### ISSUE TITLE
TSDoc: Support `@remarks` tag

### ISSUE THREAD

**Issue by RunDevelopment** [hosseinmd/prettier-plugin-jsdoc#87]
Support the [`@remarks`](https://tsdoc.org/pages/tags/remarks/) and [`@privateRemarks`](https://tsdoc.org/pages/tags/privateremarks/) TSDoc tags. They are similar to the JSDoc `@description` tag and require MD formatting.

**Comment by hosseinmd** [comment]
We have a rule for formatting descriptions which is not correct. I think we should format all tags description, so we should remove `TAGS_NEED_FORMAT_DESCRIPTION`

**Comment by hosseinmd** [comment]
What is ` @remarks` and `@privateRemarks ` order in tags.

**Comment by RunDevelopment** [comment]
> What is ` @remarks` and `@privateRemarks ` order in tags.

Right under `@description` would probably be best.
