### ISSUE TITLE
TSDoc: Support `@typeParam` tags

### ISSUE THREAD

**Issue by RunDevelopment** [hosseinmd/prettier-plugin-jsdoc#88]
The [`@typeParam` tag](https://tsdoc.org/pages/tags/typeparam/) is the TSDoc equivalent of the JSDoc `@template` tag.

They are basically equivalent but specific to TSDoc and JSDoc respectively. This plugin should __not__ treat them as synonyms. `@typeParam` and `@template` should be treated the same in all regards (e.g. tag order, grouping, and formatting).

**Comment by hosseinmd** [comment]
I fixed that with you suggest, in tsdoc example @typeParam is like @param, but type of that is generic. Is it right?

**Comment by RunDevelopment** [comment]
LGTM; Thank you!
