### ISSUE TITLE
Hyphen deletion after parameter name in "@param" block

### ISSUE THREAD

**Issue by lowkeypriority** [hosseinmd/prettier-plugin-jsdoc#9]
I'm using tsdoc plugin for ESlint. It has a rule *"The `@param` block should be followed by a parameter name and then a hyphen"*:

![image](https://user-images.githubusercontent.com/40892927/96519400-9b3ef480-1275-11eb-90e2-b6619b3a42b6.png)

When I'm trying to follow this rule and add a hyphen, I get the following error:

![image](https://user-images.githubusercontent.com/40892927/96519450-b14cb500-1275-11eb-93eb-c98df8887b58.png)

What should I do?

**Comment by hosseinmd** [comment]
I think your syntax is wrong. You should define param like this:
```js
/**
 * @param {number} name description
 */
```

**Comment by hosseinmd** [comment]
as user case
```js
/**
 * @param {number} number Returning number
 */
```

**Comment by lowkeypriority** [comment]
I'm using TSdoc and it has rule `The @param block should not include a JSDoc-style '{type}'`

Probably it is worth abandoning this plugin in favor of JSdoc :\

**Comment by hosseinmd** [comment]
Maybe we should add some options to support tsdoc

**Comment by hosseinmd** [comment]
I like tsdoc i will support it soon.

**Comment by hosseinmd** [comment]
I want to work on this thread. So could you reproduce your project? I need something to test.

**Comment by lowkeypriority** [comment]
@hosseinmd Hi
What happend?

**Comment by hosseinmd** [comment]
Hi
I need a small app with your config to work on it. I can't do it without your help.

**Comment by hosseinmd** [comment]
Or maybe if another one has this issue I will do it.
