### ISSUE TITLE
Breaks markdown tables

### ISSUE THREAD

**Issue by jasonkuhrt** [hosseinmd/prettier-plugin-jsdoc#95]
Thanks for the very promising work here! Big fan :) 

I noticed markdown tables are currently broken by this plugin.

Before:

![image](https://user-images.githubusercontent.com/284476/110524151-05e7b400-80e1-11eb-966c-7812197fcbaa.png)

![image](https://user-images.githubusercontent.com/284476/110524004-db95f680-80e0-11eb-8571-13a78fb48f65.png)

After:

![image](https://user-images.githubusercontent.com/284476/110524052-e486c800-80e0-11eb-80c3-206e5f71c539.png)

![image](https://user-images.githubusercontent.com/284476/110524136-fec0a600-80e0-11eb-96b3-cd324ba9ce89.png)

**Comment by hosseinmd** [comment]
Fixed in v0.3.14
