### ISSUE TITLE
Fix empty line before list

### ISSUE THREAD

**Issue by mtrezza** [hosseinmd/prettier-plugin-jsdoc#98]
It seems that the change in `0.3.15` introduced an empty line before a list, which seems semantically unintuitive.

For example:

```
/**
 * A description.
 *
 * @param {any} var An example list:
 * -   Item 1
 * -   Item 2
 * -   Item 3
 * @returns {Promise} A return value.
 */
```

turns into:

```
/**
 * A description.
 *
 * @param {any} var An example list:
 * 
 *   -   Item 1
 *   -   Item 2
 *   -   Item 3
 * @returns {Promise} A return value.
 */
```

This seems semantically unintuitive, because a list rarely stands on its own, unless it is an index or table of contents.

If a list should be more clearly separated from the rest, it should add an empty line before *and* after the list. But that would be even worse in my opinion, because it takes up even more space. And  the list cannot really be optically attached to the previous or following line anymore. For example, here the list seems pretty lost:

```
/**
 * A description.
 *
 * @param {any} var An example text that is
 *   long and spans multiple lines
 *   followed by a list.
 * 
 *   -   Item 1
 *   -   Item 2
 *   -   Item 3
 *
 *  And more text to come.
 * @returns {Promise} A return value.
 */
```

My suggestion would be to:
- not auto-add an empty line before or after the list
- respect if the author added an empty line before or after a list and do not remove it
- reduce the number of empty lines to 1 if the author added more than 1 empty line before or after the list

**Comment by hosseinmd** [comment]
An empty line before a list is a common behavior of md formatters like prettier md formatter. I have to say about empty line after list as well, you should add an empty line after list because if you don't add it formatter will merge that with last item of list

**Comment by hosseinmd** [comment]
> reduce the number of empty lines to 1 if the author added more than 1 empty line before or after the list

This is currently being done

**Comment by mtrezza** [comment]
I don't know what the most expected MD syntax is, but let's look at two popular MD interpreters: GitHub and Visual Studio.

## Empty line before list

```
A list:
- a
- b
```
and
```
A list:

- a
- b
```
are both displayed as:

GH:
> A list:
> - a
> - b

VSC:
<img width="136" alt="image" src="https://user-images.githubusercontent.com/5673677/113163506-87de7f00-9240-11eb-8ccb-85ca40d1682d.png">

Not adding an empty line before a list, would allow for compact "writing" of MD and leave it up to the MD interpreter how to "display" a list.  Adding an empty line seems like changing the "writing" to mimic the "displaying".

**Comment by hosseinmd** [comment]
@danielpza @RunDevelopment Please suggest.

**Comment by mtrezza** [comment]
To quickly mention another side effect after adding an empty line:

```
   /**
    * A description.
    *
    * @private
    * @param {any} This is followed by a list:
    *
    *   - List item
    *   - List item
    * @returns {any} A description.
    */
```

The positioning of the list is visually incorrect. The list is now closer positioned to `@return` than to @param` even though it belongs to `@param`.

**Comment by hosseinmd** [comment]
Myabe we should keep an empty line after list
for example 
```js
 /**
    * A description.
    *
    * @private
    * @param {any} This is followed by a list:
    *
    *   - List item
    *   - List item
    * 
    * @returns {any} A description.
    */
```

**Comment by mtrezza** [comment]
I think that would confirm the issue I mentioned previously, that prettify is behaving too much like an MD interpreter. Adding more and more empty lines to a comment section to correct visual issues is job of an interpreter I think. We are just blowing up the comment section with empty lines.

**Comment by hosseinmd** [comment]
We can't remove the empty line because of description like this:
```js

/**
 * @param {any} param0 The \`Touchable\` mixin helps you handle the "press" interaction. It analyzes
 *   the geometry of elements, and observes when another responder (scroll view
 *   etc) has stolen the touch lock. It notifies your component when it should
 *   give feedback to the user. (bouncing/highlighting/unhighlighting).
 *
 *   - When a touch was activated (typically you highlight)
 *   - When a touch was deactivated (typically you unhighlight)
 *   - When a touch was "pressed" - a touch ended while still within the geometry
 *     of the element, and no other element (like scroller) has "stolen" touch
 *     lock ("responder") (Typically you bounce the element).
 *
 *   A good tap interaction isn't as simple as you might think. There should be a
 *   slight delay before showing a highlight when starting a touch. 
 *
 *   - When a touch was activated (typically you highlight)
 *   - When a touch was deactivated (typically you unhighlight)
 *
 *   subsequent touch move exceeds the boundary of the element, it should
 *   unhighlight, but if that same touch is brought back within the boundary, it
 *   should rehighlight again. A touch can move in and out of that boundary
 *   several times, each time toggling highlighting, but a "press" is only
 *   triggered if that touch ends while within the element's boundary and no
 *   scroller (or anything else) has stolen the lock on touches.
 */
```

**Comment by mtrezza** [comment]
In that case maybe accept an empty line but not force one, and implement this before and after a list?

**Comment by mtrezza** [comment]
Maybe the difference lies in MD vs. JSDoc syntax? 

In a pure / strict MD syntax it makes sense to add an empty line before and after a list. But JSDoc has its own syntax such as tags. So an empty line after a list may not be required if the next line starts with a tag `@example`, similar to starting the next line with a MD heading `# Example`.

So similar to allowing this in MD:
```
A list:
- a
- b
### A Heading
```

would be allowing this in a JSDoc context:

```
/**
 * @param A parameter with:
 *   - a
 *   - b
 * @returns A return description.
 */
```

**Comment by hosseinmd** [comment]
I agree with. You just in this situation:
```js
/**
 * @param {any} var An example list:
 *   -   Item 1
 *   -   Item 2
 * @returns {Promise} A return value.
 */
```
If the content before of the list is one line i can remove the empty line otherwise we should add the empty line again.

```js
/**
 * @param {any} var An example list: var An example list: var An example list:
 *   var An example list: var An example list:
 *
 *   -   Item 1
 *   -   Item 2
 * @returns {Promise} A return value.
 */
```

Is this right way?

**Comment by mtrezza** [comment]
The empty line would have no effect for most if not all interpreters, I believe, the question then becomes why add it. I guess the easiest would be to say add an empty line before and after a list, in any case, just for consistency.

**Comment by hosseinmd** [comment]
I mostly agree with (a), exactly because of consistently.

**Comment by mtrezza** [comment]
I think I prefer b) because it is more compact and doesn't blow up the comment section, but either way sounds good to me

**Comment by hosseinmd** [comment]
the b) was not look good in this example:
```js
/**
 * @param {any} param0 The \`Touchable\` mixin helps you handle the "press" 
 *   the geometry of elements, and observes when another responder (scroll view
 *   etc) has stolen the touch lock. It notifies your component when it should
 *   give feedback to the user. (bouncing/highlighting/unhighlighting).
 *   - When a touch was activated (typically you highlight)
 *   - When a touch was deactivated (typically you unhighlight)
 *   - When a touch was "pressed" - a touch ended while still within the geometry
 *     of the element, and no other element (like scroller) has "stolen" touch
 *     lock ("responder") (Typically you bounce the element).
 *
 *   A good tap interaction isn't as simple as you might think. There should be a
 *   slight delay before showing a highlight when starting a touch. 
 *   - When a touch was activated (typically you highlight)
 *   - When a touch was deactivated (typically you unhighlight)
 *
 *   subsequent touch move exceeds the boundary of the element, it should
 *   unhighlight, but if that same touch is brought back within the boundary, it
 *   should rehighlight again. A touch can move in and out of that boundary
 *   several times, each time toggling highlighting, but a "press" is only
 *   triggered if that touch ends while within the element's boundary and no
 *   scroller (or anything else) has stolen the lock on touches.
 */

```

**Comment by mtrezza** [comment]
Yes, now I see it too, let's go with a) then.

**Comment by hosseinmd** [comment]
I will do it as soon as possible. Thank you for contributing.
