### ISSUE TITLE
Not compatible with `prettier-plugin-organize-imports`

### ISSUE THREAD

**Issue by electrovir** [hosseinmd/prettier-plugin-jsdoc#99]
If I install [prettier-plugin-organize-imports ](https://www.npmjs.com/package/prettier-plugin-organize-imports) and list it after `prettier-plugin-jsdoc` in the `"plugins"` array within `.prettierrc.json`, this plugin doesn't do anything at all.

**Comment by hosseinmd** [comment]
https://github.com/prettier/prettier/issues/10261

**Comment by hosseinmd** [comment]
https://github.com/prettier/prettier/issues/10259

**Comment by electrovir** [comment]
darn 😩
Thanks for the links. The more I use Prettier the more I realize it's a huge pain to work with :(

**Comment by hosseinmd** [comment]
This link show what is the problem, I solved this bug, I am improving code to resolve this for plugins more than two, I will be done so.

**Comment by hosseinmd** [comment]
Fixed: v0.3.18

**Comment by hosseinmd** [comment]
prettier-plugin-organize-imports not supporting multiple parsers for typescript so add prettier-plugin-jsdoc to end of plugins list

**Comment by electrovir** [comment]
I don't understand, what has changed?

If I list `prettier-plugin-jsdoc` last, then `prettier-plugin-jsdoc` works but `prettier-plugin-organize-imports` doesn't.
If I list `prettier-plugin-organize-imports` last then `prettier-plugin-organize-imports` works but `prettier-plugin-jsdoc` doesn't.

This is the same behavior as before the `v0.3.18` update.

**Comment by hosseinmd** [comment]
prettier can't find modules, please add plugins like. this 
```js
  "plugins": [
    "./node_modules/prettier-plugin-organize-imports",
    "./node_modules/prettier-plugin-jsdoc"
  ],
```

**Comment by electrovir** [comment]
Yes, this is my whole `.prettier.json` file:
```json
{
    "arrowParens": "always",
    "bracketSpacing": false,
    "endOfLine": "lf",
    "htmlWhitespaceSensitivity": "ignore",
    "jsdocParser": true,
    "jsonRecursiveSort": true,
    "jsxBracketSameLine": false,
    "plugins": [
        "./node_modules/prettier-plugin-sort-json",
        "./node_modules/prettier-plugin-packagejson",
        "./node_modules/prettier-plugin-organize-imports",
        "./node_modules/prettier-plugin-jsdoc"
    ],
    "printWidth": 100,
    "singleQuote": true,
    "tabWidth": 4,
    "trailingComma": "all"
}
```

And here are my dependency versions:
```
        "prettier": "^2.2.1",
        "prettier-plugin-jsdoc": "^0.3.18",
        "prettier-plugin-organize-imports": "^1.1.1",
        "prettier-plugin-packagejson": "^2.2.10",
        "prettier-plugin-sort-json": "^0.0.2",
```

**Comment by hosseinmd** [comment]
i tested that work for me, i think you should set plugins. then restart vscode to work

**Comment by electrovir** [comment]
Ah! `>Developer: Reload Window` did it. It's working now! It's also working with the Prettier CLI.

Thank you much! 😄
